spring:
  application:
    name: auth-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: guest
    password: guest
    port: ${RABBIT_PORT:5672}

server:
  port: 8081

app:
  keycloak:
    admin:
      client-id: ${APP_KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      client-secret: ${APP_KEYCLOAK_ADMIN_CLIENT_SECRET:YM3aXVjgubdyWTw3OKyZIXFDAwdGwUSL}
    user:
      client-id: ${APP_KEYCLOAK_USER_CLIENT_ID:taxi-app-client}
    realm: ${APP_KEYCLOAK_REALM:taxi-app-realm}
    server-url: ${APP_KEYCLOAK_SERVER_URL:http://localhost:9082}
    grant-type: ${APP_KEYCLOAK_GRANT_TYPE:client_credentials}

jwt:
  secret: ${JWT_SECRET:n4EpjnNy7x8FjfwYMDjPi8xYyL0EocN1uzUsfFTbLhk=}
  expire: 3

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/

springdoc:
  api-docs:
    path: /auth-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /auth-service-docs/swagger-ui
    enabled: true