server:
  port: 8087

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME:your email}
    password: ${MAIL_PASSWORD:your password}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}
    port: ${RABBIT_PORT:5672}
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type:
      redis

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/
