apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.2
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "elastic"
            - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: kibana
  type: ClusterIP
