apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config
data:
  pipeline.conf: |
    input {
    tcp {
        port => 5001
        type => syslog
        codec => json_lines
    }
    }
      
      filter {
      grok {
      match => [ "message", "%{GREEDYDATA}" ]
      }
    }
      
      output {
      stdout {
      codec => rubydebug
      }
      elasticsearch {
      hosts => [ "elasticsearch:9200" ]
      user => "elastic"
      password => "elastic"
      index => "services-logs-%{+YYYY.MM.dd}"
      }
    }
