server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/payment_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  success-url: ${FRONTEND_SUCCESS_URL:https://localhost:8086/error}
  cancel-url: ${FRONTEND_CANCEL_URL:https://localhost:8086/success}
  webhook:
    successSecretKey: ${WEBHOOK_SUCCESS_SECRET_KEY}