server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5435}/payment_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/taxi-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /payment-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /payment-service-docs/swagger-ui
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/

openapi:
  contact:
    email: artsem.maiseyenka@gmail.com
    name: Artsem Maiseyenka
  service:
    url: http://localhost:8086
    description: Payment service
  info:
    title: Payment Service
    version: 1.0
    description: This API exposes endpoints to manage balance

stripe:
  secretKey: ${STRIPE_SECRET_KEY:your-key}
  success-url: ${FRONTEND_SUCCESS_URL:https://localhost:8086/error}
  cancel-url: ${FRONTEND_CANCEL_URL:https://localhost:8086/success}
  webhook:
    successSecretKey: ${WEBHOOK_SUCCESS_SECRET_KEY:your-key}