server:
  port: 8086

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/payment_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /payment-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /payment-service-docs/swagger-ui
    enabled: true

openapi:
  contact:
    email: artsem.maiseyenka@gmail.com
    name: Artsem Maiseyenka
  service:
    url: http://localhost:8086
    description: Payment service
  info:
    title: Payment Service
    version: 1.0
    description: This API exposes endpoints to manage balance

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  success-url: ${FRONTEND_SUCCESS_URL:https://localhost:8086/error}
  cancel-url: ${FRONTEND_CANCEL_URL:https://localhost:8086/success}
  webhook:
    successSecretKey: ${WEBHOOK_SUCCESS_SECRET_KEY}