apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service-mongo-deployment
  labels:
    app: ride-service-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service-mongo
  template:
    metadata:
      labels:
        app: ride-service-mongo
    spec:
      containers:
        - name: ride-service-mongo
          image: mongo:8.0.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
            - name: MONGO_INITDB_DATABASE
              value: "ride_db"
          livenessProbe:
            httpGet:
              path: /health
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
      volumes:
        - name: mongo-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ride-service-mongo
spec:
  type: ClusterIP
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: ride-service-mongo
