server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/driver_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: driver-service

springdoc:
  api-docs:
    path: /driver-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /driver-service-docs/swagger-ui
    enabled: true