server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/driver_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: driver-service
