apiVersion: v1
kind: ConfigMap
metadata:
  name: kc-postgres-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "keycloak_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kc-postgres
  template:
    metadata:
      labels:
        app: kc-postgres
    spec:
      containers:
        - name: kc-postgres
          image: postgres:17.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: kc-postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kc-postgres-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: kc-postgres-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: kc-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: kc-postgres-data
          persistentVolumeClaim:
            claimName: kc-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kc-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: kc-postgres