server:
  port: 8084

spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: mongodb://admin:password@${MONGO_URI:localhost:27017}/ride_db?authSource=admin
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cache:
    type:
      redis
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOSTRAP_SERVERS_URI:localhost:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/taxi-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

kafka:
  topic:
    payment-process-topic:
      replicas: 1
      partitions: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/

cache:
  passenger-id:
    ttl-hours: 3
  driver-id:
    ttl-hours: 3
  distance-and-duration:
    ttl-seconds: 30

gcp:
  api:
    maps:
      key: ${MAPS_API_KEY:your-api-key}
      url: https://maps.googleapis.com/maps/api/distancematrix/json
      units: metric

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /ride-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /ride-service-docs/swagger-ui
    enabled: true

openapi:
  contact:
    email: artsem.maiseyenka@gmail.com
    name: Artsem Maiseyenka
  service:
    url: http://localhost:8084
    description: Ride service
  info:
    title: Ride Service
    version: 1.0
    description: This API exposes endpoints to manage rides