server:
  port: 8084

spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/ride_db?authSource=admin
    redis:
      host: localhost
      port: 6379
  cache:
    type:
      redis

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/taxi-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

gcp:
  api:
    maps:
      key: ${MAPS_API_KEY}
      url: https://maps.googleapis.com/maps/api/distancematrix/json
      units: metric


springdoc:
  api-docs:
    path: /ride-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /ride-service-docs/swagger-ui
    enabled: true

openapi:
  contact:
    email: artsem.maiseyenka@gmail.com
    name: Artsem Maiseyenka
  service:
    url: http://localhost:8084
    description: Ride service
  info:
    title: Ride Service
    version: 1.0
    description: This API exposes endpoints to manage rides