server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/passenger_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /passenger-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /passenger-service-docs/swagger-ui
    enabled: true