spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URI:localhost:5432}/passenger_service_db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
