server:
  port: 8085
spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://${MYSQL_URI:localhost:3306}/review_db
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:9082/realms/taxi-app-realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  client-id: review-service
  client-secret: ${CLIENT_SECRET:juE2m2BMYIkrzqLKkiVAiY1j2IusWxZQ}
  auth-server-url: ${AUTH_SERVICE_URI:http://localhost:9082/realms/taxi-app-realm/protocol/openid-connect/token}

springdoc:
  api-docs:
    path: /review-service-docs/v3/api-docs
    enabled: true
  swagger-ui:
    path: /review-service-docs/swagger-ui
    enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_URI:localhost:8761}/eureka/

openapi:
  contact:
    email: artsem.maiseyenka@gmail.com
    name: Artsem Maiseyenka
  service:
    url: http://localhost:8085
    description: Review service
  info:
    title: Review Service
    version: 1.0
    description: This API exposes endpoints to manage reviews