spring:
  application:
    name: review-service
  datasource:
    url: jdbc:mysql://${MYSQL_URI:localhost:3306}/review_db
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
