apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-deployment
  labels:
    app: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: aremm23/payment-service:3.0
          ports:
            - containerPort: 8086
          envFrom:
            - configMapRef:
                name: payment-config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 100
            periodSeconds: 100
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8086
            initialDelaySeconds: 100
            periodSeconds: 100
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30006
  selector:
    app: payment-service